// Command docgen generates the Diátaxis reference Markdown pages
// (docs/reference/{configuration,cli,metrics}.md) from the Go source
// files config.go and metrics.go.
//
// Hand-written reference docs drift from the source-of-truth silently;
// this tool extracts every flag, env var, YAML key, default, and
// Prometheus metric directly from the AST so the published reference
// is always in lock-step with the code. CI runs the generator and
// fails the build when the committed output differs.
//
// Invocation:
//
//	go generate ./...
//	# or
//	go run ./tools/docgen [-root .] [-out docs/reference]
package main

import (
	"flag"
	"fmt"
	"log"
	"os"
	"path/filepath"
)

// banner is prepended to every generated file so reviewers see at a
// glance that the document is machine-written.
const banner = "<!-- generated by tools/docgen — do not edit by hand -->"

func main() {
	var (
		root   = flag.String("root", ".", "Repository root containing config.go and metrics.go")
		outDir = flag.String("out", "docs/reference", "Output directory (relative to -root) for generated Markdown")
	)
	flag.Parse()

	info, err := parseSource(*root)
	if err != nil {
		log.Fatalf("parse source: %v", err)
	}

	files := map[string]string{
		"configuration.md": renderConfiguration(info),
		"cli.md":           renderCLI(info),
		"metrics.md":       renderMetrics(info),
	}

	outAbs := filepath.Join(*root, *outDir)
	if err := os.MkdirAll(outAbs, 0o755); err != nil {
		log.Fatalf("create output dir: %v", err)
	}
	for name, body := range files {
		path := filepath.Join(outAbs, name)
		if err := os.WriteFile(path, []byte(body), 0o644); err != nil {
			log.Fatalf("write %s: %v", path, err)
		}
		fmt.Printf("wrote %s\n", path)
	}
}
