package main

import (
	"strings"
	"testing"
)

func TestRenderDefault(t *testing.T) {
	cases := []struct {
		in, want string
	}{
		{"", ""},
		{`""`, ""},
		{`"br-ex"`, "`br-ex`"},
		{"60 * time.Second", "`60s`"},
		{"5 * time.Minute", "`5m`"},
		{"true", "`true`"},
		{"0", "`0`"},
	}
	for _, c := range cases {
		if got := renderDefault(c.in); got != c.want {
			t.Errorf("renderDefault(%q) = %q, want %q", c.in, got, c.want)
		}
	}
}

func TestRenderConfiguration_Contract(t *testing.T) {
	dir := writeFixture(t, map[string]string{
		"config.go":  configFixture,
		"metrics.go": metricsFixture,
	})
	info, err := parseSource(dir)
	if err != nil {
		t.Fatalf("parseSource: %v", err)
	}
	out := renderConfiguration(info)
	for _, want := range []string{
		"<!-- generated by tools/docgen — do not edit by hand -->",
		"| Flag | Env Var | Config key | Default | Description |",
		"| `--bridge-dev` | `OVN_NETWORK_BRIDGE_DEV` | `bridge_dev` | `br-ex` |",
		"| `--config` | `OVN_NETWORK_CONFIG` | — |  | Path to YAML config file |",
		"| `--reconcile-interval` | `OVN_NETWORK_RECONCILE_INTERVAL` | `reconcile_interval` | `60s` |",
		"## `PortForwardRule` (YAML-only)",
	} {
		if !strings.Contains(out, want) {
			t.Errorf("output missing %q\n----\n%s", want, out)
		}
	}
}

func TestRenderMetrics_Contract(t *testing.T) {
	dir := writeFixture(t, map[string]string{
		"config.go":  configFixture,
		"metrics.go": metricsFixture,
	})
	info, err := parseSource(dir)
	if err != nil {
		t.Fatalf("parseSource: %v", err)
	}
	out := renderMetrics(info)
	for _, want := range []string{
		"<!-- generated by tools/docgen — do not edit by hand -->",
		"All metrics are prefixed with `ovn_network_agent_`",
		"| `ovn_network_agent_reconcile_total` | counter (vec) | `trigger`={`event`,`periodic`,`startup`} |",
		"| `ovn_network_agent_reconcile_duration_seconds` | histogram | — |",
		"## Suggested alerts",
	} {
		if !strings.Contains(out, want) {
			t.Errorf("output missing %q\n----\n%s", want, out)
		}
	}
}

func TestRenderCLI_Contract(t *testing.T) {
	dir := writeFixture(t, map[string]string{
		"config.go":  configFixture,
		"metrics.go": metricsFixture,
	})
	info, err := parseSource(dir)
	if err != nil {
		t.Fatalf("parseSource: %v", err)
	}
	out := renderCLI(info)
	for _, want := range []string{
		"<!-- generated by tools/docgen — do not edit by hand -->",
		"| Flag | Default | Description |",
		"| `--bridge-dev` | `br-ex` | Provider bridge device |",
		"| `--reconcile-interval` | `60s` | Reconcile interval (e.g. 60s) |",
	} {
		if !strings.Contains(out, want) {
			t.Errorf("output missing %q\n----\n%s", want, out)
		}
	}
}
