changelog:
  categories:
    - title: "Features"
      labels:
        - enhancement
        - feature
    - title: "Bug Fixes"
      labels:
        - bug
        - bugfix
    - title: "Performance"
      labels:
        - performance
    - title: "Documentation"
      labels:
        - documentation
    - title: "Other Changes"
      labels:
        - "*"
  exclude:
    labels:
      - ignore
